#!/bin/bash
rootdir=$(dirname $(readlink -f $0))
datadir=$rootdir/csse_covid_19_data/csse_covid_19_daily_reports
mergefile=$rootdir/csse_covid_19_data/csse_covid_19.csv
cd $rootdir
git pull origin master
git pull upstream master
files=$(find $datadir -name *.csv | sort)
last_file=$(echo "$files"| tail -1)
header=$(head -1 $last_file | csvtool -t , -u TAB col 1,2,4- -)
dateheader=$(echo -e "Day\tLast Update")
header=$(csvtool -t TAB -u TAB paste <(echo "$dateheader") <(echo "$header"))
echo -n > $mergefile.tmp
for file in $files; do
	echo "Merging $file ..."
	data=$(tail -n +2 $file | csvtool -t , -u TAB col 3,1,2,4-8 -)
	dates=$(echo "$data" | csvtool -t TAB col 1 - | csvtool call "date +\"%m/%d/%Y %T\" -d " -)
	days=$(echo "$dates" | csvtool -t TAB col 1 - | csvtool call "date +\"%Y%m%d\" -d " -)
	# Replace first column with formatted dates
	data=$(csvtool -t TAB -u TAB pastecol 1 1 <(echo "$data") <(echo "$dates"))
	# Prepend days column
	data=$(csvtool -t TAB -u TAB paste <(echo "$days") <(echo "$data"))
	echo "$data" >> $mergefile.tmp
done
echo "Fixing country names..."
countries=$(csvtool -t TAB col 4 $mergefile.tmp)
countries=$(echo "$countries" | sed --expression 's/*//g')
countries=$(echo "$countries" | sed --expression 's/Hong Kong SAR/China/g')
countries=$(echo "$countries" | sed --expression 's/Hong Kong/China/g')
countries=$(echo "$countries" | sed --expression 's/Iran (Islamic Republic of)/Iran/g')
countries=$(echo "$countries" | sed --expression 's/occupied Palestinian territory/Palestine/g')
csvtool -t TAB -u TAB pastecol 4 1 $mergefile.tmp <(echo "$countries") > $mergefile.fixed
mv $mergefile.fixed $mergefile.tmp
echo "Sorting..."
sort -u -r $mergefile.tmp > $mergefile.sorted.desc
echo "Deduplicating..."
awk 'BEGIN {FS="\t";previd="";} {id=$1$3$4;if (id != previd) {print $0; previd=id;}}' $mergefile.sorted.desc > $mergefile.tmp
sort $mergefile.tmp > $mergefile.sorted 
echo "$header" > $mergefile
cat $mergefile.sorted >> $mergefile
rm $mergefile.tmp $mergefile.sorted $mergefile.sorted.desc
echo "Merge complete in $mergefile"
exit
echo "Committing changes to repo..."
git add $mergefile
dt=$(date +"%Y-%m-%d %T")
git commit -m "Daily reports merged at $dt. Last file processed: $(basename $last_file)."
git push origin master
echo "Completed."
